# Generated by Django 3.1.4 on 2020-12-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
