# Generated by Django 3.1.4 on 2020-12-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0002_track_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
    ]
