# Generated by Django 3.1.4 on 2020-12-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0003_remove_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_comment', to='dt_planner_app.plant'),
        ),
    ]
