# Generated by Django 3.1.4 on 2020-12-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0004_auto_20201223_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(),
        ),
    ]
