# Generated by Django 3.1.4 on 2020-12-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0005_auto_20201223_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
