# Generated by Django 3.1.4 on 2020-12-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0006_auto_20201223_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='calendar_dt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_track', to='dt_planner_app.calendar'),
            preserve_default=False,
        ),
    ]
