# Generated by Django 3.1.4 on 2020-12-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0008_history_calendar_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='dt_planner_app.user'),
            preserve_default=False,
        ),
    ]
