# Generated by Django 3.1.4 on 2020-12-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0009_comment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_dt_editor', to='dt_planner_app.user'),
            preserve_default=False,
        ),
    ]
