# Generated by Django 3.1.4 on 2020-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0010_calendar_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SE', 'Secondary')], default='SE', max_length=100),
        ),
    ]
