# Generated by Django 3.1.4 on 2020-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0011_approver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='time_zone',
            field=models.CharField(default='US/Eastern', max_length=255),
            preserve_default=False,
        ),
    ]
