# Generated by Django 3.1.4 on 2020-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_planner_app', '0013_upload'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='calendar',
            field=models.ManyToManyField(blank=True, related_name='upload_calendar', to='dt_planner_app.Calendar'),
        ),
    ]
