# Generated by Django 3.1.4 on 2020-12-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_number_game_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
    ]
