# Generated by Django 3.1.4 on 2020-12-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_dojo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due_date', models.DateTimeField(blank=True)),
                ('complete_date', models.DateTimeField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulid', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherIndividuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QADB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('short_desc', models.TextField()),
                ('Standard', models.TextField(blank=True)),
                ('desc_by', models.CharField(max_length=255)),
                ('when_desc', models.DateTimeField()),
                ('process_order', models.CharField(max_length=255)),
                ('defect_start', models.DateTimeField()),
                ('defect_end', models.DateTimeField()),
                ('product_desc', models.TextField()),
                ('brand_code', models.CharField(max_length=255)),
                ('day_code', models.CharField(max_length=255)),
                ('quanity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=100)),
                ('scrapped', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default=None, max_length=8)),
                ('steam_number', models.CharField(max_length=100)),
                ('failure_memo', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default=None, max_length=8)),
                ('need_to_hold', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default=None, max_length=8)),
                ('need_rework', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default=None, max_length=8)),
                ('root_cause', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_qadb', to='dojo_ninjas_app.action')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_qadb', to='dojo_ninjas_app.category')),
                ('other_ind_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ind_qadb', to='dojo_ninjas_app.otherindividuals')),
                ('prod_fam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_fam_qadb', to='dojo_ninjas_app.productfamily')),
                ('product_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_qadb', to='dojo_ninjas_app.producttype')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_qadb', to='dojo_ninjas_app.sector')),
                ('sector_sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sector_qadb', to='dojo_ninjas_app.subsector')),
            ],
        ),
    ]
