# Generated by Django 3.1.4 on 2020-12-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_messagemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageManager',
        ),
    ]
