# Generated by Django 3.1.4 on 2020-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
