# Generated by Django 3.1.4 on 2020-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qadb_app', '0003_auto_20201231_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCAPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='qadb',
            name='actions_capa',
            field=models.ManyToManyField(blank=True, related_name='actions_capa_qadb', to='qadb_app.Action'),
        ),
        migrations.AddField(
            model_name='qadb',
            name='attachments',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='qadb',
            name='other_ind_id',
        ),
        migrations.AddField(
            model_name='qadb',
            name='other_ind_id',
            field=models.ManyToManyField(blank=True, related_name='other_ind_qadb', to='qadb_app.OtherIndividuals'),
        ),
    ]
