# Generated by Django 3.1.4 on 2020-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qadb_app', '0004_auto_20201231_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadb',
            name='actions_capa',
            field=models.ManyToManyField(blank=True, related_name='actions_capa_qadb', to='qadb_app.ActionCAPA'),
        ),
    ]
